// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Procurement.Persistence;

#nullable disable

namespace Procurement.Persistence.Migrations
{
    [DbContext(typeof(ProcurementDbContext))]
    [Migration("20261004170709_ReliableTaskCoordination")]
    partial class ReliableTaskCoordination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AcceptedOrderVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastSubmittedVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("CreatedAt", "Id");

                    b.ToTable("purchase_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("ck_order_status", "\"Status\" IN ('Draft','Submitted','Accepted','Rejected')");

                            t.HasCheckConstraint("ck_order_version", "\"LastSubmittedVersion\" >= 0 AND (\"AcceptedOrderVersion\" IS NULL OR (\"AcceptedOrderVersion\" > 0 AND \"AcceptedOrderVersion\" <= \"LastSubmittedVersion\"))");
                        });
                });

            modelBuilder.Entity("Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("OrderId", "SkuId")
                        .IsUnique();

                    b.ToTable("order_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_line_quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Procurement.Domain.SubmittedOrderLine", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "Version", "LineId");

                    b.HasIndex("OrderId", "Version", "SkuId")
                        .IsUnique();

                    b.ToTable("order_version_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_version_line_quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Procurement.Domain.SubmittedOrderVersion", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ResolvedRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SubmittedRevision")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "Version");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("FactoryId", "SubmittedAt", "OrderId", "Version");

                    b.ToTable("order_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_submission_resolution", "(\"Status\" = 'Pending' AND \"ResolvedAt\" IS NULL AND \"ResolvedBy\" IS NULL AND \"ResolvedRevision\" IS NULL AND \"DecisionId\" IS NULL AND \"Reason\" IS NULL) OR (\"Status\" <> 'Pending' AND \"ResolvedAt\" IS NOT NULL AND \"ResolvedBy\" IS NOT NULL AND \"ResolvedRevision\" IS NOT NULL AND \"ResolvedRevision\" > \"SubmittedRevision\" AND ((\"Status\" = 'Withdrawn' AND \"DecisionId\" IS NULL) OR (\"Status\" IN ('Accepted','Rejected') AND \"DecisionId\" IS NOT NULL)) AND (\"Status\" = 'Accepted' OR (\"Reason\" IS NOT NULL AND length(btrim(\"Reason\")) > 0)))");

                            t.HasCheckConstraint("ck_submission_status", "\"Status\" IN ('Pending','Accepted','Rejected','Withdrawn')");

                            t.HasCheckConstraint("ck_submission_version", "\"Version\" > 0 AND \"SubmittedRevision\" > 0");
                        });
                });

            modelBuilder.Entity("Procurement.Persistence.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OrderVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResultRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ResultRevision", "Action")
                        .IsUnique();

                    b.ToTable("business_audit", (string)null);
                });

            modelBuilder.Entity("Procurement.Persistence.DemoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("demo_users", (string)null);
                });

            modelBuilder.Entity("Procurement.Persistence.Factory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("factories", (string)null);
                });

            modelBuilder.Entity("Procurement.Persistence.HttpRequestResult", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubjectId", "Operation", "Key");

                    b.ToTable("http_request_results", (string)null);
                });

            modelBuilder.Entity("Procurement.Persistence.ProductionTaskLink", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptedContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AcceptedOrderVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("DecisionId")
                        .IsUnique();

                    b.ToTable("production_task_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_link_status", "\"Status\" IN ('Pending','Created','Blocked')");
                        });
                });

            modelBuilder.Entity("Procurement.Persistence.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Style", "Color", "Size")
                        .IsUnique();

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("Scm.Messaging.InboxMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastError")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ConsumerName", "MessageId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("inbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_inbox_status", "\"Status\" IN ('Pending','Processed','Blocked')");
                        });
                });

            modelBuilder.Entity("Scm.Messaging.MessageFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerName", "MessageId", "Hash")
                        .IsUnique();

                    b.ToTable("message_failures", (string)null);
                });

            modelBuilder.Entity("Scm.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("EventType", "FactId")
                        .IsUnique();

                    b.HasIndex("SentAt", "NextAttemptAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Procurement.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("Procurement.Persistence.Factory", null)
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Domain.PurchaseOrderLine", b =>
                {
                    b.HasOne("Procurement.Domain.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Procurement.Persistence.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Procurement.Domain.ProductSnapshot", "Product", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Color");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Size");

                            b1.Property<string>("Style")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Style");

                            b1.HasKey("PurchaseOrderLineId");

                            b1.ToTable("order_lines");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderLineId");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Domain.SubmittedOrderLine", b =>
                {
                    b.HasOne("Procurement.Domain.SubmittedOrderVersion", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId", "Version")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Procurement.Domain.ProductSnapshot", "Product", b1 =>
                        {
                            b1.Property<Guid>("SubmittedOrderLineOrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("SubmittedOrderLineVersion")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SubmittedOrderLineLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Color");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Size");

                            b1.Property<string>("Style")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Style");

                            b1.HasKey("SubmittedOrderLineOrderId", "SubmittedOrderLineVersion", "SubmittedOrderLineLineId");

                            b1.ToTable("order_version_lines");

                            b1.WithOwner()
                                .HasForeignKey("SubmittedOrderLineOrderId", "SubmittedOrderLineVersion", "SubmittedOrderLineLineId");
                        });

                    b.Navigation("Product")
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Domain.SubmittedOrderVersion", b =>
                {
                    b.HasOne("Procurement.Persistence.Factory", null)
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Procurement.Domain.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Persistence.AuditEntry", b =>
                {
                    b.HasOne("Procurement.Domain.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Persistence.DemoUser", b =>
                {
                    b.HasOne("Procurement.Persistence.Factory", null)
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Procurement.Persistence.ProductionTaskLink", b =>
                {
                    b.HasOne("Procurement.Domain.PurchaseOrder", null)
                        .WithOne()
                        .HasForeignKey("Procurement.Persistence.ProductionTaskLink", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Procurement.Domain.SubmittedOrderVersion", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
